### ISSUE TITLE
Fix compilation for node 18

### ISSUE THREAD

**Issue by morenol** [infinyon/fluvio-client-node#288]
error is on node >= 18.14

**Comment by morenol** [comment]
It is partially related, most of the PRs like https://github.com/infinyon/fluvio-client-node/pull/286 are blocked because CI is broken for node 18

**Comment by drc-infinyon** [comment]
Okay. Got it. Was there any discussion or plan recently on what we are going to do about the broken CI?

**Comment by digikata** [comment]
I think the issue here is that compilation works, but the tests fail on versions of node 18.14+ as well as the current node 20

**Comment by digikata** [comment]
may be related to https://github.com/infinyon/node-bindgen/issues/234

**Comment by morenol** [comment]
Fixed with node-bindgen update
