### ISSUE TITLE
PartitionConsume.fetch should have an optional parameter of Offset

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio-client-node#48]
Right now [`fetch` requires an `Offset` instance](https://github.com/infinyon/fluvio-client-node/blob/e6085a6441931cd953c4b3704a0cc3769e363e40/src/index.ts#L210), this should be an optional parameter which defaults to `new Offset({index: 0, from: OffsetFrom.Beginning})` when passed into the rust.

**Comment by simlay** [comment]
@ajhunyady, @sehz this was talked about a little last week. Making the `offset` be optional is simple. What the default value should be is unclear - do you want `from` to be from the beginning or end of the stream?

**Comment by ajhunyady** [comment]
@simlay it should be from the end to be consistent with the CLI.

**Comment by simlay** [comment]
Sounds good.

**Comment by ajhunyady** [comment]
That being said, we have 2 convenience offsets, one from the beginning and one from the end. https://github.com/infinyon/fluvio-demo-apps-node/blob/master/chat-app/chat-server/src/fluvio-util.ts I found myself using both.

**Comment by sehz** [comment]
This is how it is implemented in previous version: https://github.com/infinyon/fluvio-client-node/commit/cca8e0fd1a3c57e1a2a3f032209b943d1aa88719#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26.

It accepts following format:
* Integer (offset)
* String ("earliest","latest")
* Json ( offset, start)
