### ISSUE TITLE
add API to consume with smart stream filter

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio-client-node#82]

**Comment by EstebanBorai** [comment]
I'm working on this here: https://github.com/infinyon/fluvio-client-node/pull/256

**Comment by EstebanBorai** [comment]
I think we can close this now that https://github.com/infinyon/fluvio-client-node/pull/256 is merged!

**Comment by morenol** [comment]
Thanks @EstebanBorai

**Comment by morenol** [comment]
It looks like I don't have write permissions here, could you close this? @sehz @simlay
